import time
import re


# =========================================================
# TC-STK-017
# Stack Event / Log Verification
#
# Events:
#   1. Member Join
#   2. Member Leave
#   3. MASTER Change
#   4. Stack Link Failure
#   5. Upgrade
#
# IMPORTANT:
#   - This testcase verifies ONLY REAL switch-generated logs.
#   - No fake/simulated log messages are generated.
#   - "show logging" and "show stack" are handled as paginated
#     commands because ROS7 can display:
#
#       More: <space>, Quit: q or CTRL+Z, One line: <return>
#
#   - Event validation uses a BEFORE and AFTER log snapshot so
#     old log entries are not used for the current event.
# =========================================================


TEST_CASE_ID = "TC-STK-017"

SHOW_STACK_COMMAND = "do show stack"
SHOW_LOG_COMMAND = "show logging"

STACK_WAIT_TIME = 10
MASTER_RECOVERY_WAIT = 25
LOG_CHECK_WAIT = 5

# Maximum number of pages allowed for a single command.
# This protects against an unexpected pager loop.
MAX_PAGES = 100


# =========================================================
# REAL ROS7 LOG PATTERNS
# =========================================================

# ---------------------------------------------------------
# Member JOIN / stack recovery
# ---------------------------------------------------------
MEMBER_JOIN_PATTERNS = [

    # Stack port comes UP
    r"%cscdlag-i-up:\s*stack port\s+\S+\s+operational status is up",

    # Stack port becomes active
    r"%cscdlag-i-active:\s*stack port\s+\S+\s+is active in stack lag",

    # Unit-message wrapper
    r"%stck\s+sysl-i-unitmsg:.*%cscdlag-i-up:",
    r"%stck\s+sysl-i-unitmsg:.*%cscdlag-i-active:",

    # Ring/chain topology changes
    r"%cscdlag-w-cfg-chng:.*chain to ring",
    r"%cscdlag-i-cfg-chng:.*chain to ring",
    r"%cscdlag-w-cfg-chng:.*ring to chain",
    r"%cscdlag-i-cfg-chng:.*ring to chain",

    # Explicit unit addition, if generated by the switch
    r"%stack-i-stck-unit-add:",
    r"%stack.*unit.*add.*stack",
]


# ---------------------------------------------------------
# Member LEAVE
# ---------------------------------------------------------
MEMBER_LEAVE_PATTERNS = [

    # Explicit unit removal
    r"%stack-i-stck-unit-rem:.*unit\s+\d+\s+was removed from the stack",

    # Backup unit removal
    r"%stack-i-stck-bckup-rem:.*backup unit\s+\d+\s+was removed from the stack",

    # Stack link DOWN
    r"%cscdlag-w-down:\s*stack port\s+\S+\s+operational status is down",

    # Unit-message wrapper
    r"%stck\s+sysl-w-unitmsg:.*%cscdlag-w-down:",

    # Ring changes to chain
    r"%cscdlag-w-cfg-chng:.*ring to chain",
    r"%cscdlag-i-cfg-chng:.*ring to chain",
]


# ---------------------------------------------------------
# MASTER CHANGE
#
# These are intentionally not based on generic words such
# as "active", "backup", or "master" alone.
# ---------------------------------------------------------
MASTER_CHANGE_PATTERNS = [

    r"%stack.*master.*change",
    r"%stack.*controller.*change",
    r"%stack.*master.*changed",
    r"%stack.*controller.*changed",
    r"%stack.*master.*elected",
    r"%stack.*master.*election",

    r"%stck.*master.*change",
    r"%stck.*controller.*change",

    r"master.*change",
    r"controller.*change",
    r"master.*changed",
    r"controller.*changed",
    r"master.*elected",
    r"master.*election",
]


# ---------------------------------------------------------
# STACK LINK FAILURE
# ---------------------------------------------------------
STACK_LINK_FAILURE_PATTERNS = [

    r"%cscdlag-w-down:\s*stack port\s+\S+\s+operational status is down",

    r"%stck\s+sysl-w-unitmsg:.*%cscdlag-w-down:",

    r"stack port\s+\S+\s+operational status is down",
]


# ---------------------------------------------------------
# STACK LINK RECOVERY
# ---------------------------------------------------------
STACK_LINK_RECOVERY_PATTERNS = [

    r"%cscdlag-i-up:\s*stack port\s+\S+\s+operational status is up",

    r"%cscdlag-i-active:\s*stack port\s+\S+\s+is active in stack lag",

    r"%stck\s+sysl-i-unitmsg:.*%cscdlag-i-up:",

    r"%stck\s+sysl-i-unitmsg:.*%cscdlag-i-active:",
]


# ---------------------------------------------------------
# UPGRADE
#
# Do NOT use generic "software", "version", "reload",
# or "reboot" because those can create false positives.
# ---------------------------------------------------------
UPGRADE_PATTERNS = [
    r"\bupgrade\b",
    r"firmware upgrade",
    r"software upgrade",
    r"image upgrade",
    r"install.*image",
    r"install.*firmware",
    r"upgrade.*image",
    r"upgrade.*firmware",
    r"firmware.*upgrade",
    r"software.*upgrade",
]


# =========================================================
# DISPLAY HELPERS
# =========================================================

def _print_header(title):
    print()
    print("=" * 70)
    print(title)
    print("=" * 70)


def _wait_seconds(seconds, message=None):
    if message:
        print(message)

    for remaining in range(seconds, 0, -1):
        print(
            f"\rWaiting: {remaining:>3} seconds",
            end="",
            flush=True
        )
        time.sleep(1)

    print()


def _wait_for_user(message):
    print()
    input(message)


# =========================================================
# CONNECTION COMMAND HELPERS
# =========================================================

def _send_command(conn, command):
    """
    Send a command using the existing SwitchConnection object.
    """

    if conn is None:
        return ""

    if hasattr(conn, "send_command"):
        return conn.send_command(command)

    if hasattr(conn, "execute"):
        return conn.execute(command)

    if hasattr(conn, "command"):
        return conn.command(command)

    if hasattr(conn, "send"):
        result = conn.send(command)

        if result is None:
            return ""

        return str(result)

    raise AttributeError(
        "SwitchConnection does not provide a supported "
        "command execution method."
    )


def _read_available(conn):
    """
    Try to read currently available data from the connection.
    """

    if conn is None:
        return ""

    methods = [
        "read",
        "read_all",
        "read_output",
        "receive",
        "recv",
    ]

    for method_name in methods:

        method = getattr(conn, method_name, None)

        if method is None:
            continue

        try:
            result = method()

            if result is None:
                return ""

            return str(result)

        except TypeError:
            continue

        except Exception:
            continue

    return ""


def _run_command(conn, command):
    """
    Normal command execution.
    """

    try:
        result = _send_command(conn, command)

        if result is None:
            return ""

        return str(result)

    except Exception as exc:
        print(f"Command failed: {command}")
        print(f"Error: {exc}")
        return ""


# =========================================================
# PAGINATED COMMAND SUPPORT
# =========================================================

def _contains_pager(output):
    """
    Detect ROS7 pager text.
    """

    if not output:
        return False

    patterns = [
        r"More:\s*<space>",
        r"More:\s*<space>\s*,\s*Quit:",
        r"One line:\s*<return>",
        r"Quit:\s*q\s+or\s+CTRL\+Z",
    ]

    for pattern in patterns:

        if re.search(
            pattern,
            output,
            flags=re.IGNORECASE
        ):
            return True

    return False


def _remove_pager_lines(output):
    """
    Remove pager prompt text from command output.
    """

    if not output:
        return ""

    lines = output.splitlines()
    cleaned = []

    for line in lines:

        stripped = line.strip()

        if not stripped:
            cleaned.append(line)
            continue

        if re.search(
            r"More:\s*<space>",
            stripped,
            flags=re.IGNORECASE
        ):
            continue

        if re.search(
            r"Quit:\s*q\s+or\s+CTRL\+Z",
            stripped,
            flags=re.IGNORECASE
        ):
            continue

        if re.search(
            r"One line:\s*<return>",
            stripped,
            flags=re.IGNORECASE
        ):
            continue

        cleaned.append(line)

    return "\n".join(cleaned)


def _send_space_for_pager(conn):
    """
    Continue to the next ROS7 pager page.
    """

    if conn is None:
        return ""

    methods = [
        "send",
        "write",
        "send_command",
    ]

    for method_name in methods:

        method = getattr(conn, method_name, None)

        if method is None:
            continue

        try:

            result = method(" ")

            if result is None:
                return ""

            return str(result)

        except Exception:
            continue

    return ""


def _run_paged_command(
    conn,
    command,
    timeout=30,
    max_pages=MAX_PAGES
):
    """
    Execute a command and automatically continue through ROS7
    pager pages.

    No output is fabricated. Every returned log line comes
    from the switch connection.
    """

    if conn is None:
        return ""

    collected = []

    try:

        first_output = _send_command(
            conn,
            command
        )

        if first_output:
            collected.append(str(first_output))

        start_time = time.time()
        pages = 1

        while pages < max_pages:

            current = "\n".join(collected)

            if not _contains_pager(current):
                break

            if time.time() - start_time > timeout:

                print(
                    f"WARNING: Pager timeout while running "
                    f"'{command}'."
                )

                break

            page_output = _send_space_for_pager(
                conn
            )

            if page_output:
                collected.append(
                    str(page_output)
                )

            pages += 1

            time.sleep(0.15)

        result = "\n".join(collected)

        return _remove_pager_lines(result)

    except Exception as exc:

        print(
            f"WARNING: Failed to read paginated command "
            f"'{command}': {exc}"
        )

        return "\n".join(collected)


# =========================================================
# STACK INFORMATION
# =========================================================

def _parse_stack_members(output):
    """
    Parse Unit IDs from 'show stack'.

    Supports multiple common formats.
    """

    members = set()

    if not output:
        return sorted(members)

    lines = output.splitlines()

    for line in lines:

        stripped = line.strip()

        if not stripped:
            continue

        if stripped.lower().startswith(
            (
                "show stack",
                "unit",
                "role",
                "mac",
                "state",
                "----",
                "more:",
            )
        ):
            continue

        # Example:
        # 1 MASTER ...
        # 2 BACKUP ...
        match = re.match(
            r"^\s*(\d{1,2})\s+"
            r"(?:MASTER|BACKUP|MEMBER|STANDBY|ACTIVE)\b",
            stripped,
            flags=re.IGNORECASE
        )

        if match:

            try:
                members.add(
                    int(match.group(1))
                )

            except ValueError:
                pass

            continue

        # Example:
        # UNIT ID 3
        match = re.search(
            r"\bUNIT\s+ID\s*[:=]?\s*(\d{1,2})\b",
            stripped,
            flags=re.IGNORECASE
        )

        if match:

            try:
                members.add(
                    int(match.group(1))
                )

            except ValueError:
                pass

            continue

        # Example:
        # Unit 3
        match = re.search(
            r"\bUNIT\s+(\d{1,2})\b",
            stripped,
            flags=re.IGNORECASE
        )

        if match:

            try:

                unit_id = int(
                    match.group(1)
                )

                if 1 <= unit_id <= 64:
                    members.add(unit_id)

            except ValueError:
                pass

    return sorted(members)


def _display_stack_members(
    members,
    title="Stack Members"
):
    print()
    print(title)
    print("-" * 50)

    if not members:
        print("No stack members detected.")
        return

    for unit_id in members:
        print(f"  Unit-ID {unit_id}")


def _get_stack_state(master_conn):
    """
    Read complete paginated show stack output.
    """

    output = _run_paged_command(
        master_conn,
        SHOW_STACK_COMMAND,
        timeout=30
    )

    members = _parse_stack_members(
        output
    )

    return output, members


# =========================================================
# LOGGING
# =========================================================

def _get_logging(master_conn):
    """
    Read the COMPLETE switch logging buffer.
    """

    output = _run_paged_command(
        master_conn,
        SHOW_LOG_COMMAND,
        timeout=60
    )

    return output


def _normalize_log(line):
    """
    Normalize a log line for comparison/searching.
    """

    if line is None:
        return ""

    value = str(line)

    value = value.replace(
        "\r",
        " "
    )

    value = re.sub(
        r"\s+",
        " ",
        value
    )

    return value.strip()


def _clean_log_lines(output):
    """
    Convert logging output to normalized non-empty lines.
    """

    if not output:
        return []

    result = []

    for line in output.splitlines():

        normalized = _normalize_log(
            line
        )

        if not normalized:
            continue

        if re.search(
            r"More:\s*<space>",
            normalized,
            flags=re.IGNORECASE
        ):
            continue

        result.append(normalized)

    return result


def _get_new_log_lines(
    before_output,
    after_output
):
    """
    Return only log lines that appeared after the baseline.

    Multiset-style removal is used so duplicate switch log
    messages are handled correctly.
    """

    before_lines = _clean_log_lines(
        before_output
    )

    after_lines = _clean_log_lines(
        after_output
    )

    remaining_before = {}

    for line in before_lines:

        remaining_before[line] = (
            remaining_before.get(
                line,
                0
            ) + 1
        )

    new_lines = []

    for line in after_lines:

        count = remaining_before.get(
            line,
            0
        )

        if count > 0:

            remaining_before[line] = (
                count - 1
            )

        else:

            new_lines.append(line)

    return new_lines


def _find_log_signatures(
    log_output,
    patterns
):
    """
    Find real switch-generated log lines matching
    supplied ROS7 regular expressions.
    """

    matches = []

    if not log_output:
        return matches

    lines = _clean_log_lines(
        log_output
    )

    compiled_patterns = []

    for pattern in patterns:

        try:

            compiled_patterns.append(
                re.compile(
                    pattern,
                    flags=re.IGNORECASE
                )
            )

        except re.error as exc:

            print(
                f"WARNING: Invalid log pattern "
                f"'{pattern}': {exc}"
            )

    for line in lines:

        for pattern in compiled_patterns:

            if pattern.search(line):

                if line not in matches:
                    matches.append(line)

                break

    return matches


def _find_matching_log_lines(
    log_output,
    patterns
):
    """
    Alias/helper for readability.
    """

    return _find_log_signatures(
        log_output,
        patterns
    )


def _display_ros7_log_result(
    title,
    matched_lines,
    passed=True
):
    print()
    print(title)
    print("-" * 70)

    if matched_lines:

        print(
            "REAL ROS7 SWITCH LOG MESSAGES FOUND:"
        )

        for line in matched_lines:
            print(f"  {line}")

    else:

        print(
            "No matching ROS7 switch-generated "
            "log message was found."
        )

    print()

    if passed:
        print(f"{title} : PASS")
    else:
        print(f"{title} : FAIL")


# =========================================================
# EVENT 1 - MEMBER JOIN
# =========================================================

def _test_member_join(master_conn):

    _print_header(
        "TC-STK-017.1 - MEMBER JOIN LOG VERIFICATION"
    )

    print(
        "This test verifies the REAL switch-generated logs "
        "when a stack member joins/reconnects."
    )

    print(
        "No fake log messages are generated by this testcase."
    )

    # -----------------------------------------------------
    # Baseline
    # -----------------------------------------------------

    print()
    print("Reading current stack state...")

    before_stack_output, initial_members = (
        _get_stack_state(
            master_conn
        )
    )

    _display_stack_members(
        initial_members,
        "Initial Stack Members"
    )

    print()
    print(
        "Capturing current switch logging buffer..."
    )

    before_logs = _get_logging(
        master_conn
    )

    # -----------------------------------------------------
    # User action
    # -----------------------------------------------------

    _wait_for_user(
        "\nDisconnect/reconnect the stack member as required, "
        "then press ENTER to continue..."
    )

    _wait_seconds(
        STACK_WAIT_TIME,
        "Waiting for stack/member event logs..."
    )

    # -----------------------------------------------------
    # Read current state
    # -----------------------------------------------------

    after_stack_output, members_after = (
        _get_stack_state(
            master_conn
        )
    )

    _display_stack_members(
        members_after,
        "Stack Members After Member Join"
    )

    print()
    print("Reading NEW switch logs...")

    after_logs = _get_logging(
        master_conn
    )

    new_logs = _get_new_log_lines(
        before_logs,
        after_logs
    )

    matches = _find_matching_log_lines(
        "\n".join(new_logs),
        MEMBER_JOIN_PATTERNS
    )

    # -----------------------------------------------------
    # Validation
    # -----------------------------------------------------

    print()
    print(
        f"Initial Unit-IDs : {initial_members}"
    )

    print(
        f"Current Unit-IDs : {members_after}"
    )

    new_units = sorted(
        set(members_after) -
        set(initial_members)
    )

    if new_units:

        print(
            f"New Unit-ID(s) detected: {new_units}"
        )

    else:

        print(
            "No new Unit-ID detected."
        )

        print(
            "This is allowed because the member may have "
            "reconnected using an existing Unit-ID."
        )

    stack_state_valid = True

    if initial_members and members_after:

        missing_units = sorted(
            set(initial_members) -
            set(members_after)
        )

        if missing_units:

            print(
                f"WARNING: Existing Unit-ID(s) currently "
                f"missing: {missing_units}"
            )

            stack_state_valid = False

    log_pass = bool(matches)

    _display_ros7_log_result(
        "MEMBER JOIN LOG",
        matches,
        passed=log_pass
    )

    if log_pass and stack_state_valid:

        print(
            "MEMBER JOIN RESULT : PASS"
        )

        return True

    if log_pass and not stack_state_valid:

        print(
            "MEMBER JOIN RESULT : PASS "
            "(REAL JOIN/RECOVERY LOG DETECTED)"
        )

        return True

    print(
        "MEMBER JOIN RESULT : FAIL"
    )

    return False


# =========================================================
# EVENT 2 - MEMBER LEAVE
# =========================================================

def _test_member_leave(master_conn):

    _print_header(
        "TC-STK-017.2 - MEMBER LEAVE LOG VERIFICATION"
    )

    print(
        "This test verifies the REAL switch-generated logs "
        "when a stack member leaves/is removed."
    )

    print(
        "No fake log messages are generated."
    )

    # -----------------------------------------------------
    # Baseline
    # -----------------------------------------------------

    print()
    print("Reading current stack state...")

    before_stack_output, initial_members = (
        _get_stack_state(
            master_conn
        )
    )

    _display_stack_members(
        initial_members,
        "Initial Stack Members"
    )

    print()
    print(
        "Capturing current switch logging buffer..."
    )

    before_logs = _get_logging(
        master_conn
    )

    # -----------------------------------------------------
    # User action
    # -----------------------------------------------------

    _wait_for_user(
        "\nDisconnect/remove the stack member, "
        "then press ENTER to continue..."
    )

    _wait_seconds(
        STACK_WAIT_TIME,
        "Waiting for member leave logs..."
    )

    # -----------------------------------------------------
    # Read state/logs
    # -----------------------------------------------------

    after_stack_output, members_after = (
        _get_stack_state(
            master_conn
        )
    )

    _display_stack_members(
        members_after,
        "Stack Members After Member Leave"
    )

    print()
    print(
        "Reading NEW switch logs..."
    )

    after_logs = _get_logging(
        master_conn
    )

    new_logs = _get_new_log_lines(
        before_logs,
        after_logs
    )

    matches = _find_matching_log_lines(
        "\n".join(new_logs),
        MEMBER_LEAVE_PATTERNS
    )

    # -----------------------------------------------------
    # Detect removed Unit-IDs
    # -----------------------------------------------------

    removed_units = sorted(
        set(initial_members) -
        set(members_after)
    )

    if removed_units:

        print(
            f"Removed Unit-ID(s) detected: "
            f"{removed_units}"
        )

    else:

        print(
            "No removed Unit-ID detected in the current "
            "show stack output."
        )

        print(
            "The stack may still be converging, so the "
            "switch-generated log is used as the primary "
            "event evidence."
        )

    log_pass = bool(matches)

    _display_ros7_log_result(
        "MEMBER LEAVE LOG",
        matches,
        passed=log_pass
    )

    if log_pass:

        print(
            "MEMBER LEAVE RESULT : PASS"
        )

        return True

    print(
        "MEMBER LEAVE RESULT : FAIL"
    )

    return False


# =========================================================
# EVENT 3 - MASTER CHANGE
# =========================================================

def _test_master_change(master_conn):

    _print_header(
        "TC-STK-017.3 - MASTER CHANGE LOG VERIFICATION"
    )

    print(
        "This test verifies REAL switch-generated logs "
        "for a MASTER/controller role change."
    )

    print(
        "No fake logs are generated."
    )

    # -----------------------------------------------------
    # Baseline
    # -----------------------------------------------------

    print()
    print(
        "Reading current stack state..."
    )

    before_stack_output, initial_members = (
        _get_stack_state(
            master_conn
        )
    )

    _display_stack_members(
        initial_members,
        "Initial Stack Members"
    )

    print()
    print(
        "Capturing current switch logging buffer..."
    )

    before_logs = _get_logging(
        master_conn
    )

    # -----------------------------------------------------
    # User action
    # -----------------------------------------------------

    _wait_for_user(
        "\nPerform the MASTER failover/change action, "
        "then press ENTER to continue..."
    )

    _wait_seconds(
        MASTER_RECOVERY_WAIT,
        "Waiting for MASTER change and stack recovery..."
    )

    # -----------------------------------------------------
    # Read state/logs
    # -----------------------------------------------------

    after_stack_output, members_after = (
        _get_stack_state(
            master_conn
        )
    )

    _display_stack_members(
        members_after,
        "Stack Members After MASTER Change"
    )

    print()
    print(
        "Reading NEW switch logs..."
    )

    after_logs = _get_logging(
        master_conn
    )

    new_logs = _get_new_log_lines(
        before_logs,
        after_logs
    )

    matches = _find_matching_log_lines(
        "\n".join(new_logs),
        MASTER_CHANGE_PATTERNS
    )

    # -----------------------------------------------------
    # Check stack availability
    # -----------------------------------------------------

    stack_available = bool(
        members_after
    )

    if stack_available:

        print(
            f"Stack is available after MASTER change. "
            f"Detected Unit-IDs: {members_after}"
        )

    else:

        print(
            "WARNING: No Unit-IDs detected after "
            "MASTER change."
        )

    log_pass = bool(matches)

    _display_ros7_log_result(
        "MASTER CHANGE LOG",
        matches,
        passed=log_pass
    )

    if log_pass and stack_available:

        print(
            "MASTER CHANGE RESULT : PASS"
        )

        return True

    if log_pass:

        print(
            "MASTER CHANGE RESULT : PASS "
            "(MASTER log detected)"
        )

        return True

    print(
        "MASTER CHANGE RESULT : FAIL"
    )

    return False


# =========================================================
# EVENT 4 - STACK LINK FAILURE
# =========================================================

def _test_stack_link_failure(master_conn):

    _print_header(
        "TC-STK-017.4 - STACK LINK FAILURE / RECOVERY"
    )

    print(
        "This test verifies REAL ROS7 switch-generated "
        "stack-link DOWN and UP/ACTIVE logs."
    )

    print(
        "No fake log messages are generated."
    )

    # -----------------------------------------------------
    # Initial stack state
    # -----------------------------------------------------

    print()
    print(
        "Reading initial stack state..."
    )

    initial_stack_output, initial_members = (
        _get_stack_state(
            master_conn
        )
    )

    _display_stack_members(
        initial_members,
        "Initial Stack Members"
    )

    # -----------------------------------------------------
    # Baseline logging
    # -----------------------------------------------------

    print()
    print(
        "Capturing BASELINE switch logging buffer..."
    )

    before_failure_logs = _get_logging(
        master_conn
    )

    # -----------------------------------------------------
    # User action - FAILURE
    # -----------------------------------------------------

    _wait_for_user(
        "\nDisconnect the stack cable to create the "
        "STACK LINK FAILURE, then press ENTER..."
    )

    _wait_seconds(
        STACK_WAIT_TIME,
        "Waiting for the switch to generate "
        "stack-link failure logs..."
    )

    # -----------------------------------------------------
    # Read failure logs
    # -----------------------------------------------------

    print()
    print(
        "Reading NEW switch logs for "
        "STACK LINK FAILURE..."
    )

    after_failure_logs = _get_logging(
        master_conn
    )

    new_failure_logs = _get_new_log_lines(
        before_failure_logs,
        after_failure_logs
    )

    failure_matches = _find_matching_log_lines(
        "\n".join(new_failure_logs),
        STACK_LINK_FAILURE_PATTERNS
    )

    _display_ros7_log_result(
        "STACK LINK FAILURE LOG",
        failure_matches,
        passed=bool(failure_matches)
    )

    failure_pass = bool(
        failure_matches
    )

    # -----------------------------------------------------
    # User action - RECOVERY
    # -----------------------------------------------------

    print()

    # Take a NEW baseline AFTER the failure event.
    recovery_baseline_logs = (
        after_failure_logs
    )

    _wait_for_user(
        "\nReconnect the stack cable to restore the "
        "STACK LINK, then press ENTER..."
    )

    _wait_seconds(
        STACK_WAIT_TIME,
        "Waiting for stack-link recovery..."
    )

    # -----------------------------------------------------
    # Read recovery logs
    # -----------------------------------------------------

    print()
    print(
        "Checking REAL switch recovery logs..."
    )

    recovery_logs = _get_logging(
        master_conn
    )

    new_recovery_logs = _get_new_log_lines(
        recovery_baseline_logs,
        recovery_logs
    )

    recovery_matches = _find_matching_log_lines(
        "\n".join(new_recovery_logs),
        STACK_LINK_RECOVERY_PATTERNS
    )

    _display_ros7_log_result(
        "STACK LINK RECOVERY LOG",
        recovery_matches,
        passed=bool(recovery_matches)
    )

    recovery_pass = bool(
        recovery_matches
    )

    # -----------------------------------------------------
    # Final stack state
    # -----------------------------------------------------

    print()
    print(
        "Reading final stack state..."
    )

    final_stack_output, final_members = (
        _get_stack_state(
            master_conn
        )
    )

    _display_stack_members(
        final_members,
        "Final Stack Members"
    )

    print(
        f"Final detected stack members: "
        f"{len(final_members)}"
    )

    # -----------------------------------------------------
    # Result
    # -----------------------------------------------------

    if failure_pass and recovery_pass:

        print()
        print(
            "STACK LINK FAILURE RESULT : PASS"
        )

        return True

    print()
    print(
        "STACK LINK FAILURE RESULT : FAIL"
    )

    if not failure_pass:

        print(
            "Reason: No NEW ROS7 stack-link DOWN log "
            "was detected after the failure action."
        )

    if not recovery_pass:

        print(
            "Reason: No NEW ROS7 stack-link UP/ACTIVE log "
            "was detected after the recovery action."
        )

    return False


# =========================================================
# EVENT 5 - UPGRADE
# =========================================================

def _test_upgrade(master_conn):

    _print_header(
        "TC-STK-017.5 - UPGRADE LOG VERIFICATION"
    )

    print(
        "This test verifies REAL switch-generated "
        "upgrade/firmware/image logs."
    )

    print(
        "No fake upgrade logs are generated."
    )

    # -----------------------------------------------------
    # Baseline
    # -----------------------------------------------------

    print()
    print(
        "Reading current stack state..."
    )

    before_stack_output, initial_members = (
        _get_stack_state(
            master_conn
        )
    )

    _display_stack_members(
        initial_members,
        "Initial Stack Members"
    )

    print()
    print(
        "Capturing current switch logging buffer..."
    )

    before_logs = _get_logging(
        master_conn
    )

    # -----------------------------------------------------
    # User action
    # -----------------------------------------------------

    _wait_for_user(
        "\nPerform the switch/stack upgrade operation, "
        "then press ENTER after the operation is complete..."
    )

    _wait_seconds(
        LOG_CHECK_WAIT,
        "Waiting for upgrade logs..."
    )

    # -----------------------------------------------------
    # Read new logs
    # -----------------------------------------------------

    print()
    print(
        "Reading NEW switch logs for upgrade..."
    )

    after_logs = _get_logging(
        master_conn
    )

    new_logs = _get_new_log_lines(
        before_logs,
        after_logs
    )

    matches = _find_matching_log_lines(
        "\n".join(new_logs),
        UPGRADE_PATTERNS
    )

    # -----------------------------------------------------
    # Final stack state
    # -----------------------------------------------------

    final_stack_output, final_members = (
        _get_stack_state(
            master_conn
        )
    )

    _display_stack_members(
        final_members,
        "Stack Members After Upgrade"
    )

    log_pass = bool(matches)

    _display_ros7_log_result(
        "UPGRADE LOG",
        matches,
        passed=log_pass
    )

    if log_pass:

        print(
            "UPGRADE RESULT : PASS"
        )

        return True

    print(
        "UPGRADE RESULT : FAIL"
    )

    return False


# =========================================================
# FINAL RESULT
# =========================================================

def _display_final_result(results):

    _print_header(
        "TC-STK-017 FINAL RESULT"
    )

    event_names = [
        "Member Join",
        "Member Leave",
        "MASTER Change",
        "Stack Link Failure",
        "Upgrade",
    ]

    passed_count = 0

    for index, name in enumerate(
        event_names
    ):

        result = False

        if index < len(results):
            result = bool(
                results[index]
            )

        status = (
            "PASS"
            if result
            else "FAIL"
        )

        print(
            f"{index + 1}. "
            f"{name:<25} : {status}"
        )

        if result:
            passed_count += 1

    print()

    print(
        f"Passed: {passed_count}/"
        f"{len(event_names)}"
    )

    if passed_count == len(event_names):

        print()
        print(
            "TC-STK-017 RESULT : PASS"
        )

        return True

    print()
    print(
        "TC-STK-017 RESULT : FAIL"
    )

    return False


# =========================================================
# MAIN TESTCASE ENTRY
# =========================================================

def run_tc_stk_017(
    master_conn=None,
    master_connection=None,
    master_username=None,
    master_password=None,
    connection_type=None,
    expected_members=None,
    unit1_conn=None,
    unit2_conn=None,
    switch_details=None,
    **kwargs
):
    """
    TC-STK-017 entry point.

    Compatible with the common_arguments dictionary used
    by main.py.

    IMPORTANT:
        main.py uses the parameter name 'master_connection',
        while some testcases use 'master_conn'.

        This function accepts BOTH names.

        Priority:
            1. master_conn
            2. master_connection
    """

    # =====================================================
    # FIX:
    # Accept both parameter names used by the project.
    # =====================================================

    if master_conn is None:
        master_conn = master_connection

    _print_header(
        "TC-STK-017 - Stack Event / Log Verification"
    )

    print()

    print(
        "IMPORTANT:"
    )

    print(
        "This testcase validates ONLY REAL switch-generated "
        "logs from 'show logging'."
    )

    print(
        "No SNMP traps are used."
    )

    print(
        "No fake/simulated log messages are generated."
    )

    print(
        "The testcase handles the ROS7 pager automatically."
    )

    # -----------------------------------------------------
    # Validate connection
    # -----------------------------------------------------

    if master_conn is None:

        print()

        print(
            "ERROR: MASTER connection is not available."
        )

        return False

    # -----------------------------------------------------
    # Test selection
    # -----------------------------------------------------

    print()

    print(
        "Select the event to verify:"
    )

    print()

    print(
        "1. Member Join"
    )

    print(
        "2. Member Leave"
    )

    print(
        "3. MASTER Change"
    )

    print(
        "4. Stack Link Failure / Recovery"
    )

    print(
        "5. Upgrade"
    )

    print(
        "6. Run All"
    )

    print()

    choice = input(
        "Enter your choice (1-6): "
    ).strip()

    results = []

    # -----------------------------------------------------
    # Individual event
    # -----------------------------------------------------

    if choice == "1":

        result = _test_member_join(
            master_conn
        )

        results.append(result)

        return result

    if choice == "2":

        result = _test_member_leave(
            master_conn
        )

        results.append(result)

        return result

    if choice == "3":

        result = _test_master_change(
            master_conn
        )

        results.append(result)

        return result

    if choice == "4":

        result = _test_stack_link_failure(
            master_conn
        )

        results.append(result)

        return result

    if choice == "5":

        result = _test_upgrade(
            master_conn
        )

        results.append(result)

        return result

    # -----------------------------------------------------
    # Run all
    # -----------------------------------------------------

    if choice == "6":

        print()

        print(
            "You selected RUN ALL."
        )

        print()

        print(
            "Each event will require the corresponding "
            "manual physical/action step."
        )

        _wait_for_user(
            "\nPress ENTER to start..."
        )

        results.append(
            _test_member_join(
                master_conn
            )
        )

        results.append(
            _test_member_leave(
                master_conn
            )
        )

        results.append(
            _test_master_change(
                master_conn
            )
        )

        results.append(
            _test_stack_link_failure(
                master_conn
            )
        )

        results.append(
            _test_upgrade(
                master_conn
            )
        )

        return _display_final_result(
            results
        )

    # -----------------------------------------------------
    # Invalid selection
    # -----------------------------------------------------

    print()

    print(
        "Invalid selection."
    )

    return False